=== mihawk6/PMS-TD/Testing.xsd
<?xml version="1.0" encoding="UTF-8"?>
<pms:schema xmlns:pms="http://www.w3.org/2001/XMLSchema">
<pms:element name="Testing">
<pms:complexType>
<pms:sequence>
<pms:element name="Employee" maxOccurs="unbounded">
<pms:complexType>
<pms:sequence>
<pms:element name="Name" type="pms:string"></pms:element>
<pms:element name="Emp_Id" type="pms:integer"></pms:element>
<pms:element name="Address" type="pms:string"></pms:element>
<pms:element name="Testing_cycle" type="Tcycle"></pms:element>
</pms:sequence>
</pms:complexType>
</pms:element>
</pms:sequence>
</pms:complexType>
</pms:element>
<pms:simpleType name="Tcycle">
<pms:restriction base="pms:integer">
<pms:minInclusive value="1"></pms:minInclusive>
<pms:maxInclusive value="4"></pms:maxInclusive>
</pms:restriction>
</pms:simpleType>
</pms:schema>

=== mihawk6/PMS-TD/Test2.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="test.xsl"?>
<Testing xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="Testing.xsd">
  <Employee>
    <Name>Ankur</Name>
    <Emp_Id>23</Emp_Id>
    <Address>mysore</Address>
    <Testing_cycle>2</Testing_cycle>
  </Employee>
  <Employee>
    <Name>Priyanka</Name>
    <Emp_Id>22</Emp_Id>
    <Address>Blr</Address>
    <Testing_cycle>1</Testing_cycle>
  </Employee>
  <Employee>
    <Name>Jeetank</Name>
    <Emp_Id>22</Emp_Id>
    <Address>Npr</Address>
    <Testing_cycle>4</Testing_cycle>
  </Employee>
  <Employee>
    <Name>Akshay</Name>
    <Emp_Id>21</Emp_Id>
    <Address>Delhi</Address>
    <Testing_cycle>3</Testing_cycle>
  </Employee>
  <Employee>
    <Name>Amber</Name>
    <Emp_Id>22</Emp_Id>
    <Address>Jhkd</Address>
    <Testing_cycle>2</Testing_cycle>
  </Employee>
  <Employee>
    <Name>zidane</Name>
    <Emp_Id>22</Emp_Id>
    <Address>RM</Address>
    <Testing_cycle>2</Testing_cycle>
  </Employee>
</Testing>
