=== mihawk6/PMS-TD/CAT2/index.xsd
<?xml version="1.0" encoding="UTF-8"?>
<pms:schema xmlns:hms="http://www.w3.org/2001/XMLSchema">
	<pms:element name="Christ">
		<pms:complexType>
			<pms:sequence>
				<pms:element name="ComputerScience" maxOccurs="unbounded">
					<pms:complexType>
						<pms:sequence>
						
							<pms:element name="Student_name" type="pms:string"></pms:element>
							<pms:element name="Student_university" type="pms:string"></pms:element>
							<pms:element name="Student_phone" type="pms:integer"></pms:element>
							<pms:element name="Student_email" type="pms:string"></pms:element>
							
						</pms:sequence>
					</pms:complexType>
				</pms:element>
			</pms:sequence>		
		</pms:complexType>
	</pms:element>
</pms:schema>

=== mihawk6/PMS-TD/CAT2/dom1.xml
<?xml version="1.0" encoding="UTF-8"?>
<Christ xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="index.xsd">
<ComputerScience>
    <Student_name>Adi Singh</Student_name>
    <Student_university>Christ university</Student_university>
    <Student_phone>5687457889</Student_phone>
    <Student_email>adi@gmail.com</Student_email>
</ComputerScience>
<ComputerScience>
    <Student_name>Ruben verma</Student_name>
    <Student_university>VIT university</Student_university>
    <Student_phone>5687457834</Student_phone>
    <Student_email>rubi@gmail.com</Student_email>
</ComputerScience>
  
  <ComputerScience>
    <Student_name>bhanu Singh</Student_name>
    <Student_university>IIT university</Student_university>
    <Student_phone>8287457459</Student_phone>
    <Student_email>bhanu@gmail.com</Student_email>
</ComputerScience>

</Christ>
